"""Seed script — inserts one sample company, user, property, and knowledge chunks.

Usage:
    cd services/api
    DATABASE_URL=postgresql+asyncpg://postgres:postgres@localhost:5432/waxwing

The inserted UUIDs are deterministic so the script is idempotent — re-running it
will hit the UNIQUE constraint on `id` and skip without duplicating data.
"""

import asyncio
import os
import uuid

from pathlib import Path

from dotenv import load_dotenv
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker, create_async_engine

# Resolve .env relative to this file: tests/fixtures/ -> repo root -> services/api/.env
load_dotenv(Path(__file__).resolve().parents[2] / "services" / "api" / ".env")

# ---------------------------------------------------------------------------
# Deterministic UUIDs — stable across runs so Akhil and Alex can hardcode them
# ---------------------------------------------------------------------------
COMPANY_ID = uuid.UUID("00000000-0000-0000-0000-000000000001")
USER_ID = uuid.UUID("00000000-0000-0000-0000-000000000002")
PROPERTY_ID = uuid.UUID("00000000-0000-0000-0000-000000000003")
CHUNK_IDS = [uuid.UUID(f"00000000-0000-0000-0000-{i:012d}") for i in range(4, 9)]


async def seed(session: AsyncSession) -> None:
    from sqlalchemy import text

    # Use raw SQL to keep the seed independent of ORM import order issues
    await session.execute(
        text("""
            INSERT INTO companies (id, name, created_at, updated_at)
            VALUES (:id, :name, now(), now())
            ON CONFLICT (id) DO NOTHING
        """),
        {"id": str(COMPANY_ID), "name": "Demo Property Management Co."},
    )

    await session.execute(
        text("""
            INSERT INTO users (id, company_id, name, email, role, status, created_at, updated_at)
            VALUES (:id, :company_id, :name, :email, :role, :status, now(), now())
            ON CONFLICT (id) DO NOTHING
        """),
        {
            "id": str(USER_ID),
            "company_id": str(COMPANY_ID),
            "name": "Demo Admin",
            "email": "admin@sunsetapartments.example",
            "role": "admin",
            "status": "active",
        },
    )

    await session.execute(
        text("""
            INSERT INTO properties (
                id, company_id, name, address, description,
                amenities, office_hours, leasing_policies,
                maintenance_instructions, escalation_contacts,
                business_hour_rules, call_handling_rules,
                created_at, updated_at
            )
            VALUES (
                :id, :company_id, :name, :address, :description,
                CAST(:amenities AS JSONB), CAST(:office_hours AS JSONB), :leasing_policies,
                :maintenance_instructions, CAST(:escalation_contacts AS JSONB),
                CAST(:business_hour_rules AS JSONB), CAST(:call_handling_rules AS JSONB),
                now(), now()
            )
            ON CONFLICT (id) DO NOTHING
        """),
        {
            "id": str(PROPERTY_ID),
            "company_id": str(COMPANY_ID),
            "name": "Sunset Apartments",
            "address": "123 Sunset Blvd, Austin, TX 78701",
            "description": "Modern multifamily community in central Austin with 120 units.",
            "amenities": '{"pool": true, "gym": true, "parking": "covered", "pet_friendly": true, "rooftop_deck": true, "coworking_lounge": true}',
            "office_hours": '{"mon_fri": "9:00 AM - 6:00 PM", "sat": "10:00 AM - 4:00 PM", "sun": "closed"}',
            "leasing_policies": "12-month minimum lease. First and last month required at signing. Application fee $75. Credit check required. Minimum income 3x monthly rent.",
            "maintenance_instructions": "Submit requests via the resident portal at residents.sunsetapts.example or call the emergency maintenance line at +15125550911.",
            "escalation_contacts": '[{"name": "Jane Smith", "phone": "+15125550100", "role": "Property Manager", "email": "jane@sunsetapts.example"}, {"name": "Bob Torres", "phone": "+15125550911", "role": "Emergency Maintenance", "available": "24/7"}]',
            "business_hour_rules": '{"timezone": "America/Chicago", "after_hours_start": "18:00", "after_hours_end": "09:00"}',
            "call_handling_rules": '{"after_hours_message": "Thank you for calling Sunset Apartments. Our office is currently closed. For emergencies, press 1. To leave a leasing inquiry, press 2.", "escalate_after_seconds": 45}',
        },
    )

    # Seed 5 knowledge chunks with dummy embeddings (all zeros).
    # Real embeddings are generated by the Phase 3 RAG pipeline.
    dummy_embedding = "[" + ",".join(["0.0"] * 1536) + "]"
    chunks = [
        (
            CHUNK_IDS[0],
            "Pet Policy: Pets are welcome at Sunset Apartments. We accept cats and dogs up to 75 lbs. Breed restrictions apply (no Pit Bulls, Rottweilers, or Dobermans). Monthly pet rent is $50 per pet. Non-refundable pet fee of $300.",
            "Leasing Policies & Pet Rules, p.2",
        ),
        (
            CHUNK_IDS[1],
            "Parking: Covered parking is included with every unit at no additional cost. One spot per unit. Guest parking is available on the surface lot on a first-come, first-served basis.",
            "Community Amenities Guide, p.5",
        ),
        (
            CHUNK_IDS[2],
            "Unit Pricing (as of May 2026): Studio — $1,450/month. 1 Bedroom — $1,750/month. 2 Bedroom — $2,200/month. Prices subject to availability and may vary by floor and view.",
            "Current Rent Roll, May 2026",
        ),
        (
            CHUNK_IDS[3],
            "Lease Terms: Standard lease is 12 months. 6-month leases available at a $150/month premium. Month-to-month available after initial lease at $250/month premium with 60-day notice required.",
            "Leasing Policies & Pet Rules, p.1",
        ),
        (
            CHUNK_IDS[4],
            "Move-In Requirements: First month's rent, last month's rent, and a security deposit equal to one month's rent are due at lease signing. Acceptable payment methods: certified check, money order, or ACH transfer.",
            "Leasing Policies & Pet Rules, p.3",
        ),
    ]

    for chunk_id, chunk_text, source_label in chunks:
        await session.execute(
            text("""
                INSERT INTO knowledge_chunks (
                    id, document_id, property_id, company_id,
                    chunk_text, source_label, page_number, embedding, created_at
                )
                VALUES (
                    :id,
                    CAST('00000000-0000-0000-0000-000000000099' AS UUID),
                    :property_id, :company_id,
                    :chunk_text, :source_label, NULL,
                    CAST(:embedding AS vector),
                    now()
                )
                ON CONFLICT (id) DO NOTHING
            """),
            {
                "id": str(chunk_id),
                "property_id": str(PROPERTY_ID),
                "company_id": str(COMPANY_ID),
                "chunk_text": chunk_text,
                "source_label": source_label,
                "embedding": dummy_embedding,
            },
        )

    await session.commit()
    print("Seed complete.")
    print(f"  COMPANY_ID  = {COMPANY_ID}")
    print(f"  USER_ID     = {USER_ID}")
    print(f"  PROPERTY_ID = {PROPERTY_ID}")


async def main() -> None:
    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        raise RuntimeError("DATABASE_URL environment variable is not set")
    if database_url.startswith("postgresql://"):
        database_url = database_url.replace("postgresql://", "postgresql+asyncpg://", 1)

    engine = create_async_engine(database_url, echo=False)
    async_session = async_sessionmaker(engine, expire_on_commit=False)
    async with async_session() as session:
        await seed(session)
    await engine.dispose()


if __name__ == "__main__":
    asyncio.run(main())
