"""
LLMAdapter protocol — the stable interface all LLM adapters must implement.

The locked LLM is Gemini-2.0 Flash (docs/03-tooling-and-guardrails.md). The protocol
exists so that:
  1. Tests inject MockLLMAdapter without network calls.
  2. A future model swap (ADR required) only touches the adapter class, not
     the LiveKit worker entrypoint or VoiceSession.

Design notes
------------
- System prompt is passed separately from conversation history so the LLM adapter
  can map it to the correct API field (Gemini: systemInstruction; OpenAI: system role).
- Conversation history is a list of Message dicts with 'role' and 'content'.
  Roles are 'user' (caller) and 'assistant' (agent). The adapter translates these
  to the provider's native roles (Gemini: 'user'/'model').
- Responses are yielded as string tokens to support streaming. The worker
  accumulates tokens into a full response before sending to TTS. Partial tokens
  are available for future latency optimisations (e.g., start TTS on first sentence).
- cancel() must abort an in-progress streaming response. The worker uses this
  during barge-in (caller starts speaking while agent is generating a response).

Safety rules encoded here
-------------------------
The LLM adapter itself is not responsible for safety guardrails — that is the
VoiceSession + EscalationDetector + system prompt responsibility. However the
adapter MUST:
  - Never inject additional system instructions beyond what is passed in.
  - Never cache responses across calls (each call is stateless at the adapter level).
  - Not log the system_prompt or conversation_history (PII risk).

Usage::

    adapter: LLMAdapter = GeminiLLMAdapter(api_key=...)
    full_text = ""
    async for token in adapter.respond_streaming(system_prompt, history):
        full_text += token
    # On barge-in:
    await adapter.cancel()
"""

from __future__ import annotations

from typing import AsyncIterator, Protocol, TypedDict, runtime_checkable


class Message(TypedDict):
    """
    A single message in a conversation history.

    Attributes:
        role:    'user' for caller turns, 'assistant' for agent turns.
        content: The text content of the message.
    """

    role: str   # 'user' | 'assistant'
    content: str


@runtime_checkable
class LLMAdapter(Protocol):
    """
    Protocol for streaming LLM adapters.

    Adapters must be safe for sequential use within a single call session
    (one respond_streaming call active at a time). The cancel() method
    must be idempotent — calling it when no stream is active is a no-op.
    """

    async def respond_streaming(
        self,
        system_prompt: str,
        conversation_history: list[Message],
    ) -> AsyncIterator[str]:
        """
        Generate a streaming response given a system prompt and conversation history.

        Yields string tokens as they arrive from the LLM. Callers should accumulate
        tokens to build the full response before passing to TTS. However, a future
        optimisation can pipe the first complete sentence to TTS early.

        Safety requirement: the system_prompt passed here is the Waxwing leasing
        assistant prompt. Do NOT yield tokens that were not generated by the model
        in response to this prompt.

        Args:
            system_prompt:         The full system instruction for the agent role.
            conversation_history:  Ordered list of prior turns (oldest first).
                                   Each entry has 'role' and 'content'.

        Yields:
            str: Response token or token chunk. May be partial words.

        Raises:
            LLMProviderError: On unrecoverable generation failure.
        """
        ...  # pragma: no cover

    async def cancel(self) -> None:
        """
        Abort the current streaming response (barge-in support).

        Must be safe to call even if no generation is in progress.
        After cancel(), a new respond_streaming() call must work
        without needing to recreate the adapter.
        """
        ...  # pragma: no cover


class LLMProviderError(Exception):
    """
    Raised by LLM adapters on unrecoverable generation failures.

    Attributes:
        message:     Human-readable description.
        retryable:   True if the caller may retry after a short wait.
                     4xx errors (except 429) are not retryable.
                     5xx and 429 are retryable.
        status_code: HTTP status code from the provider, if available.
    """

    def __init__(
        self,
        message: str,
        retryable: bool = False,
        status_code: int | None = None,
    ) -> None:
        super().__init__(message)
        self.message = message
        self.retryable = retryable
        self.status_code = status_code

    def __repr__(self) -> str:
        return (
            f"LLMProviderError(message={self.message!r}, "
            f"retryable={self.retryable}, status_code={self.status_code})"
        )
